/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSerahTerimaRouteImport } from './routes/_authenticated/serah-terima'
import { Route as AuthenticatedPengumumanRouteImport } from './routes/_authenticated/pengumuman'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedJadwalRouteImport } from './routes/_authenticated/jadwal'
import { Route as AuthenticatedIzinCutiRouteImport } from './routes/_authenticated/izin-cuti'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAbsensiRouteImport } from './routes/_authenticated/absensi'
import { Route as AuthenticatedJadwalStaffIdRouteImport } from './routes/_authenticated/jadwal_.$staffId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSerahTerimaRoute =
  AuthenticatedSerahTerimaRouteImport.update({
    id: '/serah-terima',
    path: '/serah-terima',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengumumanRoute = AuthenticatedPengumumanRouteImport.update({
  id: '/pengumuman',
  path: '/pengumuman',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJadwalRoute = AuthenticatedJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIzinCutiRoute = AuthenticatedIzinCutiRouteImport.update({
  id: '/izin-cuti',
  path: '/izin-cuti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAbsensiRoute = AuthenticatedAbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJadwalStaffIdRoute =
  AuthenticatedJadwalStaffIdRouteImport.update({
    id: '/jadwal_/$staffId',
    path: '/jadwal/$staffId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/absensi': typeof AuthenticatedAbsensiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/izin-cuti': typeof AuthenticatedIzinCutiRoute
  '/jadwal': typeof AuthenticatedJadwalRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/pengumuman': typeof AuthenticatedPengumumanRoute
  '/serah-terima': typeof AuthenticatedSerahTerimaRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/jadwal/$staffId': typeof AuthenticatedJadwalStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/absensi': typeof AuthenticatedAbsensiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/izin-cuti': typeof AuthenticatedIzinCutiRoute
  '/jadwal': typeof AuthenticatedJadwalRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/pengumuman': typeof AuthenticatedPengumumanRoute
  '/serah-terima': typeof AuthenticatedSerahTerimaRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/jadwal/$staffId': typeof AuthenticatedJadwalStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/absensi': typeof AuthenticatedAbsensiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/izin-cuti': typeof AuthenticatedIzinCutiRoute
  '/_authenticated/jadwal': typeof AuthenticatedJadwalRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/pengumuman': typeof AuthenticatedPengumumanRoute
  '/_authenticated/serah-terima': typeof AuthenticatedSerahTerimaRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/jadwal_/$staffId': typeof AuthenticatedJadwalStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/absensi'
    | '/dashboard'
    | '/izin-cuti'
    | '/jadwal'
    | '/kalender'
    | '/laporan'
    | '/pengaturan'
    | '/pengumuman'
    | '/serah-terima'
    | '/staff'
    | '/jadwal/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/absensi'
    | '/dashboard'
    | '/izin-cuti'
    | '/jadwal'
    | '/kalender'
    | '/laporan'
    | '/pengaturan'
    | '/pengumuman'
    | '/serah-terima'
    | '/staff'
    | '/jadwal/$staffId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/absensi'
    | '/_authenticated/dashboard'
    | '/_authenticated/izin-cuti'
    | '/_authenticated/jadwal'
    | '/_authenticated/kalender'
    | '/_authenticated/laporan'
    | '/_authenticated/pengaturan'
    | '/_authenticated/pengumuman'
    | '/_authenticated/serah-terima'
    | '/_authenticated/staff'
    | '/_authenticated/jadwal_/$staffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/serah-terima': {
      id: '/_authenticated/serah-terima'
      path: '/serah-terima'
      fullPath: '/serah-terima'
      preLoaderRoute: typeof AuthenticatedSerahTerimaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengumuman': {
      id: '/_authenticated/pengumuman'
      path: '/pengumuman'
      fullPath: '/pengumuman'
      preLoaderRoute: typeof AuthenticatedPengumumanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jadwal': {
      id: '/_authenticated/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof AuthenticatedJadwalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/izin-cuti': {
      id: '/_authenticated/izin-cuti'
      path: '/izin-cuti'
      fullPath: '/izin-cuti'
      preLoaderRoute: typeof AuthenticatedIzinCutiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/absensi': {
      id: '/_authenticated/absensi'
      path: '/absensi'
      fullPath: '/absensi'
      preLoaderRoute: typeof AuthenticatedAbsensiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jadwal_/$staffId': {
      id: '/_authenticated/jadwal_/$staffId'
      path: '/jadwal/$staffId'
      fullPath: '/jadwal/$staffId'
      preLoaderRoute: typeof AuthenticatedJadwalStaffIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAbsensiRoute: typeof AuthenticatedAbsensiRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIzinCutiRoute: typeof AuthenticatedIzinCutiRoute
  AuthenticatedJadwalRoute: typeof AuthenticatedJadwalRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPengumumanRoute: typeof AuthenticatedPengumumanRoute
  AuthenticatedSerahTerimaRoute: typeof AuthenticatedSerahTerimaRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedJadwalStaffIdRoute: typeof AuthenticatedJadwalStaffIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAbsensiRoute: AuthenticatedAbsensiRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIzinCutiRoute: AuthenticatedIzinCutiRoute,
  AuthenticatedJadwalRoute: AuthenticatedJadwalRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPengumumanRoute: AuthenticatedPengumumanRoute,
  AuthenticatedSerahTerimaRoute: AuthenticatedSerahTerimaRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedJadwalStaffIdRoute: AuthenticatedJadwalStaffIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
